---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: molecule-vm-ubuntu2404-ansible
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ""
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  # env:
  #   ANSIBLE_VERBOSITY: 2

verifier:
  name: ansible

lint: |
  ansible-lint --exclude molecule/default/
